### ISSUE TITLE
Can't return focus to vim

### ISSUE THREAD

**Issue by MatrixManAtYrService** [ervandew/screen#30]
I use `:call g:ScreenShellFocus()` to bring focus to the new pane that `:ScreenShell` created, but then I can't get back to vim.

Some searching indicates that `C-a C-a` should switch to the latest window (and (maybe?) back to vim) but this just places the string: `^A^A` at the shell.  I remapped `C-a` to `C-b` in `.screenrc`, which allows me to invoke the gnu-screen control options, but it still doesn't work.

`C-b C-a` does nothing
`C-b w` brings up a list of screens, but it only contains one item, so there's nothing to switch to.

I tried switching to tmux, and found similar behavior.  Sorry if I'm missing something obvious, but is there a way to switch back to vim once I've sent focus to screen or tmux?

The behavior is similar whether or not I'm already in a screen session.

**Comment by ervandew** [comment]
In gnu screen `c-a c-a` is for switching windows, but in this case you want to switch regions, so you can use `c-a <tab>` (`c-b <tab>` if you're remapped `c-a`).

In tmux you'd be switching panes, but tmux uses `;` instead of `<tab>`, so if you are using the default prefix of `c-b`, then you'd use `c-b ;`.
